apiVersion: v1
kind: Namespace
metadata:
  name: node-js
  labels:
    mesh: node-js
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: appmesh-system
  labels:
    mesh: node-js
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled